var group___d_a_t_a_b_a_s_e_s =
[
    [ "DB_SQL_BASE", "class_d_b___s_q_l___b_a_s_e.html", null ],
    [ "DB_SQL_CONNECTION", "class_d_b___s_q_l___c_o_n_n_e_c_t_i_o_n.html", null ],
    [ "DB_SQL_DATABASE", "class_d_b___s_q_l___d_a_t_a_b_a_s_e.html", null ],
    [ "DB_SQL_ERROR", "class_d_b___s_q_l___e_r_r_o_r.html", null ],
    [ "DB_SQL_FACTORY", "class_d_b___s_q_l___f_a_c_t_o_r_y.html", null ],
    [ "DB_SQL_QUERY", "class_d_b___s_q_l___q_u_e_r_y.html", null ],
    [ "DB_SQL_RESULT", "class_d_b___s_q_l___r_e_s_u_l_t.html", null ],
    [ "DB_SQL_VARIANT", "class_d_b___s_q_l___v_a_r_i_a_n_t.html", null ],
    [ "MYSQL_CONNECTION", "class_m_y_s_q_l___c_o_n_n_e_c_t_i_o_n.html", null ],
    [ "MYSQL_DATABASE", "class_m_y_s_q_l___d_a_t_a_b_a_s_e.html", null ],
    [ "MYSQL_QUERY", "class_m_y_s_q_l___q_u_e_r_y.html", null ],
    [ "MYSQL_RESULT", "class_m_y_s_q_l___r_e_s_u_l_t.html", null ],
    [ "MYSQL_VARIANT", "class_m_y_s_q_l___v_a_r_i_a_n_t.html", null ],
    [ "POSTGRESQL_CONNECTION", "class_p_o_s_t_g_r_e_s_q_l___c_o_n_n_e_c_t_i_o_n.html", null ],
    [ "POSTGRESQL_DATABASE", "class_p_o_s_t_g_r_e_s_q_l___d_a_t_a_b_a_s_e.html", null ],
    [ "POSTGRESQL_QUERY", "class_p_o_s_t_g_r_e_s_q_l___q_u_e_r_y.html", null ],
    [ "POSTGRESQL_RESULT", "class_p_o_s_t_g_r_e_s_q_l___r_e_s_u_l_t.html", null ],
    [ "SQLITE_CONNECTION", "class_s_q_l_i_t_e___c_o_n_n_e_c_t_i_o_n.html", null ],
    [ "SQLITE_DATABASE", "class_s_q_l_i_t_e___d_a_t_a_b_a_s_e.html", null ],
    [ "SQLITE_QUERY", "class_s_q_l_i_t_e___q_u_e_r_y.html", null ],
    [ "SQLITE_RESULT", "class_s_q_l_i_t_e___r_e_s_u_l_t.html", [
      [ "~SQLITE_RESULT", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#aff86c5c9583793e55996f155593b3e51", null ],
      [ "SQLITE_RESULT", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#a5795de8ba5a986e6b159777dcc362725", null ],
      [ "Abort", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#aa6cb6845e5a938fd05869ba6a4fd6cba", null ],
      [ "First", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#a4e58eba300febcd793eec44c2d1fbdd7", null ],
      [ "GetNumColumns", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#a58eb99e01742bdcb174f11fe3df8d855", null ],
      [ "GetNumRows", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#a8ca534c39a6460b1b4a82a50ac0f62fc", null ],
      [ "HasNext", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#a70fccc84457d2abbf085a095ef3989d9", null ],
      [ "Last", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#a818017703c7badadded5d19426937882", null ],
      [ "Next", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#aed5704de24930ea14886315bc94746b2", null ],
      [ "ProcessRow", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#a2a940f779e97b00eceb850d671978b57", null ],
      [ "Seek", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#a7713a77b17c3bdc1d1b51bb5b65b606f", null ],
      [ "SQLITE_QUERY", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#a51e1b0af52f80f702535dea7bf69e50a", null ],
      [ "lastresult", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#afbb79a577b2dd9763daf2bfc2ab38af0", null ],
      [ "query", "class_s_q_l_i_t_e___r_e_s_u_l_t.html#a4cf2262ff95d750e19ef8cd94f1978f0", null ]
    ] ]
];